name: Deploy to Digital Ocean 

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: SSH to DigitalOcean and deploy
      uses: appleboy/ssh-action@v0.1.7
      with:
        host: '134.209.219.161'
        username: 'root'
        password: 'TonikakuK1B' 
        port: 22
        script: |
          cd ~/domotica
          git pull origin master
          docker-compose down
          docker-compose up -d --build